# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=10, null=True)),
                ('gtype', models.IntegerField(max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
