# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('gw_ip', models.CharField(max_length=32)),
                ('port', models.IntegerField(max_length=11)),
                ('user', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('file_name', models.CharField(max_length=10, null=True)),
                ('state', models.SmallIntegerField(default=1, max_length=1, null=True)),
                ('feature', models.IntegerField(default=0, max_length=11)),
                ('run', models.IntegerField(default=0, max_length=11)),
                ('apply_time', models.IntegerField(default=0, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='new_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10)),
                ('type', models.IntegerField(max_length=10)),
                ('vm_id', models.IntegerField(max_length=10)),
                ('ip', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=30)),
                ('lid', models.IntegerField(max_length=10)),
                ('apply_time', models.IntegerField(max_length=10)),
                ('state', models.SmallIntegerField(default=0, max_length=1)),
                ('log_admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='new_vm_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=11)),
                ('gateway_ip', models.CharField(max_length=20)),
                ('region', models.IntegerField(default=0, max_length=11)),
                ('vm_id', models.IntegerField(max_length=11)),
                ('os_version', models.CharField(max_length=50)),
                ('cpu_cores', models.IntegerField(max_length=2)),
                ('memory', models.IntegerField(max_length=10)),
                ('disk', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('lid', models.IntegerField(max_length=11)),
                ('apply_time', models.IntegerField(max_length=11)),
                ('state', models.IntegerField(max_length=2)),
                ('log_admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.IntegerField(default=0, max_length=10, null=True)),
                ('uuid', models.CharField(max_length=60, null=True)),
                ('name_label', models.CharField(max_length=50, null=True)),
                ('type', models.IntegerField(default=1, max_length=5, null=True)),
                ('cpu_cores', models.IntegerField(default=0, max_length=3)),
                ('memory', models.IntegerField(default=0, max_length=3)),
                ('disk', models.IntegerField(default=0, max_length=10)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('gateway_ip', models.CharField(max_length=15, null=True)),
                ('region', models.IntegerField(max_length=11)),
                ('os_version', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=100)),
                ('user', models.IntegerField(max_length=10, null=True)),
                ('apply_time', models.IntegerField(default=0, max_length=11, null=True)),
                ('start_time', models.IntegerField(default=0, max_length=11, null=True)),
                ('power_state', models.CharField(max_length=20, null=True)),
                ('state', models.SmallIntegerField(default=0, max_length=1, null=True)),
                ('delete', models.SmallIntegerField(default=1, max_length=1, null=True)),
                ('log_admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vm_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(max_length=11)),
                ('os_version', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vm_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=11, null=True)),
                ('vm_id', models.CharField(max_length=32, null=True)),
                ('des_ip', models.CharField(max_length=32, null=True)),
                ('local_port', models.IntegerField(max_length=10, null=True)),
                ('gw_ip', models.CharField(max_length=32, null=True)),
                ('port', models.IntegerField(max_length=10, null=True)),
                ('state', models.SmallIntegerField(default=0, max_length=1, null=True)),
                ('timeout', models.SmallIntegerField(default=0, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20, null=True)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('gateway_ip', models.CharField(max_length=15, null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('pwd', models.CharField(max_length=20, null=True)),
                ('belong', models.IntegerField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ws_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.CharField(max_length=10)),
                ('cpuNumber', models.IntegerField(max_length=32)),
                ('cpuSpeed', models.IntegerField(max_length=32)),
                ('totalMemory', models.IntegerField(max_length=32)),
                ('overheadMemory', models.IntegerField(max_length=32)),
                ('freeMemory', models.IntegerField(max_length=32)),
                ('physicalDisk', models.IntegerField(max_length=32)),
                ('virtualAllocation', models.IntegerField(max_length=32)),
                ('physicalUtilisation', models.IntegerField(max_length=32)),
            ],
        ),
    ]
